### ISSUE TITLE
Error message trigger?

### ISSUE THREAD

**Issue by denizulku** [Viva-con-Agua/donation-form#96]
Moini

Es scheint, als würden einige Spender:innen Errormessages für ihre SEPA-Spenden kriegen. Laut Stripe sind die aber durchgegangen, entsprechende Bestätigungen haben die Spender:innen auch per Mail von Stripe gekriegt. Sie sind nur nicht im CRM zu finden. Mir ist im Code so kein Fehler bei den Trigger aufgefallen, sieht alles eig fein aus. Hier paar Beispiele (insgesamt sind es 8 Fälle, wollte aber nicht alle IDs in ein public repo reinhauen 😄 - hab alle IDs notiert, fragt mich gerne, wenn ihr die braucht):

Dauerspenden:
84A9DDF0-661E-4399-8DDF-AAF8E8010627

Einzelspenden:
0b666695-cb97-40ca-ad95-39d68cb59817

Vielen Dank!

**Comment by deinelieblings** [comment]
Das ein Service war zweitweise Down. Ich bin alle Fälle mal durch gegangen und das lag auf jeden Fall an dem Service
